/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

// 動作設計
// P10 -- R1 -+- D1 -- P12
//            +- P11 (ADC)
// 1, P10 を H, P12 を L で P11 で Vf を測定
// 2, P12 を H, P10 を L で P11 で Vdd-Vr を測定

#define _VDD 5.0
#define DEBUG 0

int main(void)
{
  float Vf; 
  float Vr; 

  EI();

  // P10, P12 をデジタルモードに
  // コンフィグレータでできるんだけど I2C, ADC のからみでやたらと複雑だし、自分でやるほう
  // がすっきり
  PMCA1_bit.no0 = 0;
  PMCA1_bit.no2 = 0;

  // PM10, 12 を出力に
  PM1_bit.no0 = 0;
  PM1_bit.no2 = 0;
   
  #if DEBUG == 1
  R_Config_UART1_Start();
  #endif 

  OreLCDBegin();    

  // Vf の測定
  // P10 を H, P12 を L
  P1_bit.no0 = 1;
  P1_bit.no2 = 0;

  // チキンウェイト
  R_BSP_SoftwareDelay(1, BSP_DELAY_MILLISECS);

  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();

  Vf = _VDD * ( (float)(ADCR0)+0.5)/4096.0 ;

  #if DEBUG == 1
  OreUART1_Send_U16(ADCR0);
  OreUART1_Send_CRLF();
  #endif

  // Vr の測定
  // P10 を L, P12 を H に
  P1_bit.no0 = 0;
  P1_bit.no2 = 1;

  // チキンウェイト
  R_BSP_SoftwareDelay(1, BSP_DELAY_MILLISECS);

  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();

  Vr = _VDD * ( (float)(4096-ADCR0)-0.5)/4096.0 ;

  #if DEBUG == 1
  OreUART1_Send_U16(ADCR0);
  OreUART1_Send_CRLF();
  #endif

  // LCD に表示
  OreLCD_Char(0b01010110); //"V"
  OreLCD_Char(0b01100110); //"f"
  OreLCD_Char(0b00111010); //":"
  OreLCD_Char(0b00100000); //" "
  OreLCD_Float(Vf, 3);
  OreLCD_Char(0b01010110); //"V"

  OreLCD_Locate(1,0); //2行目の先頭に

  OreLCD_Char(0b01010110); //"V"
  OreLCD_Char(0b01110010); //"r"
  OreLCD_Char(0b00111010); //":"
  OreLCD_Char(0b00100000); //" "
  OreLCD_Float(Vr, 3); 
  OreLCD_Char(0b01010110); //"V"

  if(Vr<Vf){
    OreLCD_Char(0b00100000); //" "
    OreLCD_Char(0b00111111); //"?"
  };
  
  return 0;
}


