/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
//#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

int main(void)
{
  EI();
   
  R_Config_UART1_Start();

  while(1){
    R_Config_ADC_Start();
    while(ADCS==1){};
    R_Config_ADC_Stop();
    OreUART1_Send_U16(ADCR0);
    OreUART1_Send_CRLF();
    R_BSP_SoftwareDelay(1, BSP_DELAY_SECS);
  };

  //OreLCDBegin();    
  //// テスト動作確認済み
  //char a[5]="hello";
  //OreLCD_Print(a,5); 
  //OreLCD_Locate(1,0); //2行目の先頭に
  ////OreLCD_Char(0b11110100); // Ω
  ////OreLCD_Float(-1.23456e-20, 5);
  //OreLCD_Float(1.23456e20, 6);
  //OreLCD_Uint16(1234);
  return 0;
}


