/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : UART_send.c
*  Description  : Main Program
*  Creation Date: 2025-10-07
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

int main(void);
volatile uint8_t _uart_end;

#define OreUART1_Send_Txt_test 0
#define OreUART1_Send_U16_test 0
#define OreUART1_Send_Float_test 1

int main(void)
{
	EI();
  R_Config_UART1_Start();
  _uart_end=0;
  
  #if OreUART1_Send_Txt_test == 1
  char text[7]="hello\r\n";
  while(1){
    OreUART1_Send_Txt( (unsigned char *)text,7);
  };
  #endif 

  #if OreUART1_Send_U16_test == 1
  uint16_t num = 0;
  while(1){
    for(num=0; num<=0b1111111111111111; num++){
      OreUART1_Send_U16(num);
      OreUART1_Send_CRLF( );
    };
  };
  #endif

  #if OreUART1_Send_Float_test == 1
  while(1){
    // 最小は 
    OreUART1_Send_Float(-1.2345678e-20, 5);
    OreUART1_Send_CRLF( );
    OreUART1_Send_Float(-1.2345678e20, 5);
    OreUART1_Send_CRLF( );
    OreUART1_Send_Float(1.2345678e-20, 5);
    OreUART1_Send_CRLF( );
    OreUART1_Send_Float(1.2345678e20, 5);
    OreUART1_Send_CRLF( );
  };
  #endif
  return 0;
}
