/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

#define DEBUG 0 //0: しない, 1: 軽く, 2: ガチ

int main(void)
{
  float vout;
  EI();

  // 多分スマコンの自動生成でもそうなってると思うけど、念のため
  P2_bit.no2 = 1; // pMos 閉じる

  #if DEBUG >= 1
  R_Config_UART1_Start();
  #endif 

  OreLCDBegin();    

  // ADC 空打ち
  // なんか起動直後の 1回目は変な値を取る気がする。
  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();
  
  P2_bit.no2 = 0; // pMOS 開く

  // コンデンサが 6.8uF. 
  // 電源は 2A 行けるから、とりあえずインピーダンスは 2.5Ωと見ておこう
  // 5τで 99.3% 充電だから、5x2.5x6.8u = 8.5e-5 sec 
  // 丸めて 10μsec
  // 安全見て 100μs でいいな
  R_BSP_SoftwareDelay(100, BSP_DELAY_MICROSECS );

  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();

  vout=(  (float)(ADCR0) + 0.5)/4096.0 * 5.0;

  #if DEBUG >= 1
  OreUART1_Send_U16(ADCR0);
  OreUART1_Send_ASCII(',');
  OreUART1_Send_Float(vout, 5);
  OreUART1_Send_CRLF();
  #endif 

  OreLCD_CLS();
  OreLCD_Fixed(vout, 5);
  OreLCD_Char(0b00100000); //" "
  OreLCD_Char(0b01010110); //"V" 

  // 電源入れっぱなしだと交換できないから、適当に LED 光らせておいてから落とす
  R_BSP_SoftwareDelay( 1000, BSP_DELAY_MILLISECS);
  P2_bit.no2 = 1; // pMOS クローズ
  
  while(1){};

  return 0;
}
