/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

#define _VDD 5.0
#define DEBUG 0

int main(void)
{
  uint16_t Ev; //明さ[Lx]
  EI();
   
  #if DEBUG == 1
  R_Config_UART1_Start();
  #endif 

  OreLCDBegin();    

  while(1){
    // ADC の測定
    R_Config_ADC_Start();
    while(ADCS==1){};
    R_Config_ADC_Stop();

    #if DEBUG == 1
    OreUART1_Send_U16(ADCR0);
    OreUART1_Send_CRLF();
    #endif

    // Ev[Lx] の計算
    Ev = (uint16_t) (ADCR0 * 0.2);
    #if DEBUG == 1
    OreUART1_Send_U16( Ev );
    OreUART1_Send_CRLF();
    #endif
    
    // LCD に表示
    OreLCD_Uint16( Ev );
    OreLCD_Char(0b00100000); //" "
    OreLCD_Char(0b01001100); //"L"
    OreLCD_Char(0b01111000); //"x"

    R_BSP_SoftwareDelay(10, BSP_DELAY_SECS);
    OreLCD_CLS();
  };

  return 0;
}

// 何も考えずに浮動小数点演算やってるから 17KB
