/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

#define _VDD 5.0
#define DEBUG 0 //0: しない, 1: 軽く, 2: ガチ

// main の流れ
// 1. PWM を動かす (ずっと）
// 2. ADC を動かす (ずっと繰り返す)
// 3. 最大値を更新する
// 4. ADC を指定回数動かしたら、出力
// 5. 最大値をリセット

// ADC をこれだけ回したら、最大値を出力して、adc_max=0 にリセット
// 多分 adc 1回は 16usec
#define _adc_max_count 65535

int main(void)
{
  uint16_t adc_max=0; // adc の最大値を格納
  uint16_t adc_count=0; // adc を何回回したか、カウント
  EI();
   
  #if DEBUG >= 1
  R_Config_UART1_Start();
  #endif 

  OreLCDBegin();    

  // ADC 空打ち
  // なんか起動直後の 1回目は変な値を取る気がする。
  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();

  // PWM 開始
  // スマートコンフィグレータの書く関数の基本動作原理は、開始要求だけで、開始を待たない
  // でも雑に ADC を回し続けるだけだし、別に気にしなくて良いでしょう。
  R_Config_TAU0_0_Start();

  while(1){
    // ここからが本番

    for(adc_count=0; adc_count < _adc_max_count; adc_count++){
      // ADC の測定
      R_Config_ADC_Start();
      while(ADCS==1){};
      R_Config_ADC_Stop();

      #if DEBUG == 2  // 毎回の出力は本気のときだけ
      OreUART1_Send_U16(ADCR0);
      OreUART1_Send_CRLF();
      #endif

      // ADC 最大値の判定
      if ( adc_max < ADCR0 ) {
        adc_max = ADCR0;
      } 
    }

    // 指定回数 ADC を回したから、ポスト処理だ
    #if DEBUG >= 1
    OreUART1_Send_U16( adc_max );
    OreUART1_Send_CRLF();
    #endif
    
    // LCD に表示
    OreLCD_CLS();
    OreLCD_Uint16( adc_max );
    //OreLCD_Char(0b00100000); //" "
    //OreLCD_Char(0b01001100); //"L"
    //OreLCD_Char(0b01111000); //"x"

    // 評価の見せ方は、おいおい考えよう。

    adc_max=0; // reset
  }

  return 0;
}

